apiVersion: v1
kind: Namespace
metadata:
  name: mcgonagle

---

apiVersion: v1
kind: Namespace
metadata:
  name: mcgonagle-fleet-manifest-example

---

apiVersion: v1
kind: Namespace
metadata:
  name: mcgonagle-fleet-helm-example
