     - uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GH_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: 3,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Ran postman_cloudflare_graphql.yml Successfully!'
            })
